# Generated by Django 4.0.4 on 2022-06-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCount',
            fields=[
                ('user_count_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app_id', models.CharField(max_length=255)),
                ('device_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
